# To activate, change the Appveyor settings to use `.appveyor.yml`.
install:
  - python -m pip install --upgrade setuptools tox virtualenv

build: off

test_script:
  - python -m tox -e py27,py36,py37,dogfood
