# To activate, change the Appveyor settings to use `.appveyor.yml`.
install:
  - python -m pip install tox

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - python -m tox -e py27,py34,py35,dogfood
