name: main

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py310"]'
      os: windows-latest
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["pypy3", "py310", "py311", "py312", "py313", "py314", "py315"]'
      os: ubuntu-latest
  main-other:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["docs", "linters", "dogfood"]'
      os: ubuntu-latest
